name: Continuos Deployment workflow

on:
  push:
    branches:
    - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
      - name: Use SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.Lemoncode}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Git config
        run: |
          git config --global user.email "adritwist@gmail.com"
          git config --global user.name "adritwist"
      - name: Install
        run: npm run build
      - name: Deploy
        run: npm run deploy -- -r git@github.com:adritwist/Modulo-Cloud-Ejercicio2.git