name: Continuos Deployment workflow

on:
  push:
    branches:
    - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm run build
      - name: Deploy
        run: npm run deploy